# Some Basic Numpy Array Functions

---
- numpy.arange - Return evenly spaced values within a given interval.
- numpy.reshape - Gives a new shape to an array without changing its data.
- numpy.split - Split an array into multiple sub-arrays.
- numpy.column_stack - Stack 1-D arrays as columns into a 2-D array.
- numpy.concatenate - Join a sequence of arrays along an existing axis.


In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ········
[jovian] Updating notebook "ankush-kulashri/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/ankush-kulashri/numpy-array-operations


'https://jovian.ml/ankush-kulashri/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [ ]:
import numpy as np

In [ ]:
Function 1 = numpy.arange
Function 2 = numpy.reshape
Function 3 = numpy.split
Function 4 = numpy.column_stack
Function 5 = numpy.concatenate

## Function 1 - numpy.arange

This functions or routine, generates or returns evenly spaced numbers in the given interval

In [ ]:
# Example 1
x = np.arange(0,10,0.1)

print("X contains:{}, and has total of {} elements.\n".format(x,len(x)))

X contains:[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9], and has total of 100 elements.



Here we have used ***arange*** to generate evenly spaced numbers from 0 to 10  with a common difference of 0.1 and since we've provided 10 as upper limit, it is not included in the array.
In function, first argument is 0 which is initial value we will have our array.
Second arguement is the upper limit.
Third arguement is used to determine total size of the array.

In [ ]:
# Example 2
y=np.arange(10,1,-1)

print("Y contains:{}, and has total of {} elements.\n".format(y,len(y)))

Y contains:[10  9  8  7  6  5  4  3  2], and has total of 9 elements.



This example is similar to previous one but, here we are generating a array in reverse, ie. in decreasing order

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
z= np.arange(start=0)
z= np.arange(stop=10)

TypeError: ignored

Program breaks because in ***arange*** function we can give one arguement but that has to be only for 'start' ie first arguement.
In simpler words we need to pass two arguements if we want to include 'stop' or second arguement.

eg. np.arange(0,10) will generate array of 10 elements starting from 0 to 9, also step value or difference between any two consecutive elements in this case is 1.

It is useful when our requirement to generate elements in array is of indices.

In [ ]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/ankush-kulashri/numpy-array-operations


'https://jovian.ml/ankush-kulashri/numpy-array-operations'

## Function 2 - numpy.reshape

Reshapes an array in to desired dimension

In [ ]:
# Example 1 - working
org_a = np.arange(0,16)
res_a = org_a.reshape(4,4)

print("Original Array:\n{}\nReshaped Array:\n{}".format(org_a,res_a))

Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshaped Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Here the array of 1X16 is reshaped to 4X4 array

In [ ]:
# Example 2 - working
res_b = res_a.reshape(8,2)
print("Final Reshaped Array:\n{}".format(res_b))

Final Reshaped Array:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


Here array is reshaped from 4X4 to 8X2

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
res_c = res_b.reshape(4,2)


ValueError: ignored

This program breaks because array formed before and after reshape must have equal number of elements, as our original array has 16 elements so to reshape it we either need to add or delete some elements.
eg. if we want to reshape a 16 elementa array into 4X2 array then , we would need to split that array in two 8 elements array each to be reshaped in 4X2.

We can use numpy's split() to divide array in n number of equal parts

This approach is useful when data is huge any we want to divide it in several parts to process it efficiently

In [ ]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/ankush-kulashri/numpy-array-operations


'https://jovian.ml/ankush-kulashri/numpy-array-operations'

## Function 3 - numpy.split

Splitting an array in equal parts

In [ ]:
# Example 1 - working
split_org = np.split(org_a,4)
split_org

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15])]

Splitting an array in 4 equal parts

In [ ]:
# Example 2 - working
split_res_a = np.split(res_a,4)
split_res_a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

Splitting a 4X4 array in 4 equal parts

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
split = np.split(res_a,3)

ValueError: ignored

Program breaks because function cannot divide 16 elements in 3 equal parts, we can resolve it either by adding or deleting elements in the array to match it with the resulting array.

In [ ]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/ankush-kulashri/numpy-array-operations


'https://jovian.ml/ankush-kulashri/numpy-array-operations'

## Function 4 - numpy.column_stack

This function arranges two or more 1D array of equal size as a column stack ie each array passed as arguement are arranged as column for the new 2D array

In [ ]:
# Example 1 - working
col1 = np.arange(0,4)
col2 = np.arange(4,8)
col3 = np.arange(8,12)
col4 = np.arange(12,16)

col = np.column_stack((col1,col2,col3,col4))
col

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

Here we have formed a column stack of our arrays

In [ ]:
# Example 2 - working
sta1 = np.arange(3,7).reshape(2,2)
sta2 = np.arange(0,4).reshape(2,2)
print(np.column_stack((sta1,sta2)))

[[3 4 0 1]
 [5 6 2 3]]


This is similar to above example, but here we've reshaped it to 2X2 then stacked them.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
col5 = col1.reshape(2,2)
stack = np.column_stack((col5,col1))

ValueError: ignored

We cannot stack two array which has different dimensions, as our first array has dimension of 2X2 but second array has dimension of 1X4, or both have different axis.
We can resolve this by reshaping them matching axis or equal dimensions.

In [ ]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/ankush-kulashri/numpy-array-operations


'https://jovian.ml/ankush-kulashri/numpy-array-operations'

## Function 5 - numpy.concatenate

This function combines or joins two or more array.

In [ ]:
# Example 1 - working
a= np.arange(0,16).reshape(4,4)
b= np.arange(16,32).reshape(4,4)
con = np.concatenate((a,b))
con

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

Two 4X4 arrays are merged according to default axis=0, ie in vertical axis.

In [ ]:
# Example 2 - working
con_1 = np.concatenate((a,b),axis=1)
con_1

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

Two 4X4 arrays are merged accoding to axis=1, in this case horizontal axis 


In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
con_2 = np.concatenate((a,b),axis=2)

AxisError: ignored

Here axis=2, does not exist in any or both the arrays, so our program has broken.
We need to correctly define the axis present in them.





In [79]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/ankush-kulashri/numpy-array-operations


'https://jovian.ml/ankush-kulashri/numpy-array-operations'

## Conclusion

This notebook has some useful array creation and manipulation functions, these forms basis while dealing with data strutured in array format.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* W3Schools.com : [https://www.w3schools.com/python/numpy_intro.asp](https://www.w3schools.com/python/numpy_intro.asp)


In [4]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ankush-kulashri/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/ankush-kulashri/numpy-array-operations


'https://jovian.ml/ankush-kulashri/numpy-array-operations'